# Generated by Django 5.2.9 on 2025-12-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_delete_activationcode'),
        ('ai_service', '0002_alter_airequest_user'),
        ('core', '0002_remove_appuser_user_remove_appuser_workspace_and_more'),
        ('ecom', '0002_alter_inventorytransaction_performed_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_user_id'], name='idx_tg_user_telegram'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['email'], name='idx_tg_user_email'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['phone'], name='idx_tg_user_phone'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['role'], name='idx_tg_user_role'),
        ),
        migrations.AddIndex(
            model_name='planactivationcode',
            index=models.Index(fields=['code'], name='idx_plan_code'),
        ),
        migrations.AddIndex(
            model_name='planactivationcode',
            index=models.Index(fields=['is_used'], name='idx_plan_is_used'),
        ),
        migrations.AddIndex(
            model_name='planactivationcode',
            index=models.Index(fields=['expires_at'], name='idx_plan_expires'),
        ),
    ]
