# Generated by Django 5.2.9 on 2025-12-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_appuser_telegramuser_idx_tg_user_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='has_used_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planactivationcode',
            name='plan_name',
            field=models.CharField(choices=[('Free', 'Free Plan'), ('Free Trial', 'Free Trial (7 Days)'), ('Pro', 'Pro Plan'), ('Max', 'Max Plan')], max_length=20),
        ),
    ]
