# Generated by Django 5.2.9 on 2025-12-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegramuser_has_used_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table='workspace',
        ),
    ]
