# Generated by Django 5.2.9 on 2025-12-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationCode',
        ),
    ]
