branch-defaults:
  default:
    environment: bot-management-prod
    group_suffix: null
environment-defaults:
  bot-management-prod:
    branch: null
    repository: null
global:
  application_name: bot-management-system
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
