# Generated by Django 5.2.9 on 2025-12-19 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='core.workspace')),
            ],
            options={
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='core.workspace')),
            ],
            options={
                'db_table': 'ai_prompt_template',
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('response_preview', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_service.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workspace')),
            ],
            options={
                'db_table': 'ai_request',
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.CharField(max_length=500)),
                ('ai_answer', models.TextField()),
                ('source_model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='core.workspace')),
            ],
            options={
                'db_table': 'ai_response',
            },
        ),
        migrations.CreateModel(
            name='AIModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violations', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='ai_service.airesponse')),
            ],
            options={
                'db_table': 'ai_moderation',
            },
        ),
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'db_table': 'ai_document',
                'indexes': [models.Index(fields=['workspace'], name='idx_aidoc_workspace')],
            },
        ),
        migrations.CreateModel(
            name='AIEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk', models.TextField()),
                ('vector', models.JSONField()),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.workspace')),
            ],
            options={
                'db_table': 'ai_embedding',
                'indexes': [models.Index(fields=['workspace'], name='idx_aiembedding_workspace'), models.Index(fields=['source_type'], name='idx_aiembedding_source_type')],
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['name'], name='idx_aimodel_name'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider'], name='idx_aimodel_provider'),
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['workspace'], name='idx_prompt_workspace'),
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['is_active'], name='idx_prompt_active'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['workspace', 'created_at'], name='idx_aireq_workspace_created'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['workspace'], name='idx_airesponse_workspace'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['source_model'], name='idx_airesponse_source'),
        ),
        migrations.AddIndex(
            model_name='aimoderation',
            index=models.Index(fields=['ai_response'], name='idx_aimod_response'),
        ),
    ]
