# Generated by Django 5.2.9 on 2025-12-20 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
        ('core', '0002_remove_appuser_user_remove_appuser_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramuser'),
        ),
    ]
