# Generated by Django 5.2.9 on 2025-12-19 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique activation code', max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('PRO', 'Pro Plan'), ('MAX', 'Max Plan')], help_text='Subscription plan type', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Code expiration date (optional)', null=True)),
            ],
            options={
                'db_table': 'subscription_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_name', models.CharField(max_length=255)),
                ('telegram_token', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('interactions_count', models.PositiveIntegerField(default=0)),
                ('questions_count', models.PositiveIntegerField(default=0)),
                ('active_users_count', models.PositiveIntegerField(default=0)),
                ('welcome_message', models.TextField(default='👋 Welcome to our bot! How can we help you?')),
                ('fallback_message', models.TextField(default="❗Sorry, I couldn't find an answer to that.")),
                ('working_hours_start', models.TimeField(default='08:00')),
                ('working_hours_end', models.TimeField(default='22:00')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=20)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('enable_ai_mode', models.BooleanField(default=False)),
                ('home_keyboard_type', models.CharField(choices=[('INLINE', 'Inline Keyboard'), ('REPLY', 'Reply Keyboard')], default='INLINE', help_text='Default keyboard style for the main menu', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_settings',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keyboard_type', models.CharField(choices=[('INLINE', 'Inline Keyboard'), ('REPLY', 'Reply Keyboard')], default='INLINE', help_text='How to display subcategories/questions for this category', max_length=10)),
                ('bot', models.ForeignKey(blank=True, help_text='Bot this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bot_app.botsettings')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bot_app.faqcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_faq_categories', to='core.workspace')),
            ],
            options={
                'db_table': 'bot_faq_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, help_text='Bot this FAQ belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='bot_app.botsettings')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_faqs', to='core.workspace')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='bot_app.faqcategory')),
            ],
            options={
                'db_table': 'bot_faq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bot_app.faqcategory')),
            ],
            options={
                'db_table': 'bot_page',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('contact_bot_username', models.CharField(blank=True, help_text='Bot username to contact (without @). If empty, uses the main bot.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, help_text='Attachments included in this group', related_name='page_groups', to='core.attachment')),
            ],
            options={
                'db_table': 'bot_page_group',
                'ordering': ['created_at'],
            },
        ),
    ]
