# Generated by Django 5.2.9 on 2025-12-19 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0001_initial'),
        ('ecom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegroup',
            name='medicines',
            field=models.ManyToManyField(blank=True, help_text='Medicines included in this group', related_name='page_groups', to='ecom.medicine'),
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='page',
            field=models.ForeignKey(help_text='Page this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='bot_app.botpage'),
        ),
        migrations.AddField(
            model_name='subscriptioncode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='botsettings',
            index=models.Index(fields=['workspace_name'], name='bot_setting_workspa_4e7c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='botsettings',
            index=models.Index(fields=['is_active'], name='bot_setting_is_acti_02553d_idx'),
        ),
        migrations.AddIndex(
            model_name='botsettings',
            index=models.Index(fields=['is_connected'], name='bot_setting_is_conn_0bf225_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['bot'], name='idx_faqcat_bot'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['bot'], name='idx_faq_bot'),
        ),
    ]
