# Generated by Django 5.2.9 on 2025-12-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionCode',
        ),
    ]
