# Generated by Django 5.2.9 on 2025-12-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_delete_subscriptioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='start_keywords',
            field=models.TextField(default='hi,hello,hey,start,Hi,Hello,Hey,Start,مرحبا,السلام عليكم,أهلا,اهلا,أهلا وسهلا', help_text='Comma-separated list of keywords that trigger the welcome message'),
        ),
    ]
