# Generated by Django 5.2.9 on 2025-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_botsettings_start_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='start_keywords',
            field=models.TextField(blank=True, default='hi,hello,hey,start,Hi,Hello,Hey,Start,مرحبا,السلام عليكم,أهلا,اهلا,أهلا وسهلا', help_text='Comma-separated list of keywords that trigger the welcome message'),
        ),
    ]
