"""
Django settings for bot_management_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# import pymysql
# pymysql.install_as_MySQLdb()


from pathlib import Path
import os

# PyMySQL as MySQLdb replacement (DISABLED - use native mysqlclient)
# import pymysql
# pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file directly reliably
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                k, v = line.split('=', 1)
                os.environ[k.strip()] = v.strip(' "\'')

# Helper function to get environment variables with defaults and type casting
def get_env(key, default=None, cast=None):
    """Get environment variable with default and optional type casting"""
    value = os.environ.get(key, default)
    if cast and value is not None:
        if cast == bool:
            return value.lower() in ('true', '1', 'yes', 'on') if isinstance(value, str) else bool(value)
        return cast(value)
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('SECRET_KEY', default='django-insecure-^q)or%!3_vx1u+q)qw!j*!m#qa3s$ql+47_5xitzbt1%xc!=2l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration - FORCE ALLOW ALL for troubleshooting
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'pharmacy_app.apps.PharmacyAppConfig',
    'bot_app.apps.BotAppConfig',
    'admin_app.apps.AdminAppConfig',
    'home_app',

    # New model-only apps
    'core',
    'ecom',
    'ai_service',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
        'django.contrib.staticfiles',
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Storage
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bot_app.middleware.BotSelectionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Required for django.contrib.sites (needed by django-allauth)
SITE_ID = 1

ROOT_URLCONF = 'bot_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],         
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bot_app.context_processors.bot_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'bot_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if we're using RDS (production) or local database
if 'RDS_DB_NAME' in os.environ:
    # Production: AWS RDS MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('RDS_DB_NAME'),
            'USER': os.environ.get('RDS_USERNAME'),
            'PASSWORD': os.environ.get('RDS_PASSWORD'),
            'HOST': os.environ.get('RDS_HOSTNAME'),
            'PORT': os.environ.get('RDS_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            },
        }
    }
else:
    # Development: Local MySQL
    DATABASES = {
        'default': {
            'ENGINE': get_env('DB_ENGINE', default='django.db.backends.mysql'),
            'NAME': get_env('DB_NAME', default='bot_management_db'),
            'USER': get_env('DB_USER', default='admin'),
            'PASSWORD': get_env('DB_PASSWORD', default='secure_password_123!'),
            'HOST': get_env('DB_HOST', default='localhost'),
            'PORT': get_env('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'use_unicode': True,
            } if get_env('DB_ENGINE', default='django.db.backends.mysql') == 'django.db.backends.mysql' else {}
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# AWS S3 settings
USE_S3 = get_env('USE_S3', default=False, cast=bool)

if USE_S3:
    # AWS S3 Settings
    AWS_ACCESS_KEY_ID = get_env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = get_env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = get_env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = get_env('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'public-read'
    AWS_LOCATION = 'static'
    
    # Static files settings
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # Media files settings
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
else:
    # Local development settings
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [BASE_DIR / "static"]
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Static root for collectstatic (required for production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise settings for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not USE_S3 else STATICFILES_STORAGE


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py


# LOGIN_URL = '/owner/login/'  # Redirect to owner login for @login_required



# LOGIN_REDIRECT_URL = '/owner/dashboard/'

LOGIN_URL = '/owner/login/'
LOGIN_REDIRECT_URL = '/owner/dashboard/'
LOGOUT_REDIRECT_URL = '/owner/login/'
# settings.py
TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, "templates")]


# Allauth Configuration
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # Show account selection every time
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none'


# Production Security Settings
if not DEBUG:
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = False
    
    # Session security
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 0  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # Other security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Add your Elastic Beanstalk URL to CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = get_env(
        'CSRF_TRUSTED_ORIGINS',
        default='',
        cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
    )
